### ISSUE TITLE
Packaging repo out of sync with the Debian archive

### ISSUE THREAD

**Issue by nicoonoclaste** [Yubico/libu2f-host-dpkg#2]
While preparing #1, I didn't realize that the git history is out-of-sync with the packages that have actually been uploaded to the Debian archive:
- A NMU (v1.0.0-1.1, 2016-03-02) was missing from the repo (actual changes, changelog, ...).
- A number of things worked on in 2015 were simply never uploaded to Debian.

For the sake of getting a less confusing history, I suggest we reset to the current state of https://github.com/nbraud/libu2f-host-dpkg (commit b493c1b9da4db50a4dd7b537828d699e4aa7d886).

**Comment by nevun** [comment]
Closing this issue because we are archiving this repo since it is not maintainted anymore. Debian packages are currently built from: https://salsa.debian.org/auth-team/libu2f-host
